FROM openjdk:8-jdk-alpine
VOLUME /tmp
ADD ./target/eureka1-0.0.1-SNAPSHOT.jar eureka1-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/eureka1-0.0.1-SNAPSHOT.jar"]