version: '3'
services:
  backend:
    build:
      context: C:\Users\amino\OneDrive\Bureau\Architecture MSA\GestionTerrainMS
      dockerfile: C:\Users\amino\OneDrive\Bureau\Architecture MSA\GestionTerrainMS\dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mabasededonnes
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mabasededonnes:3306/terrain
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: amine

  mabasededonnes:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: amine
      MYSQL_DATABASE: terrain

  eurekaserver:
    build:
      context: C:\Users\amino\OneDrive\Bureau\Architecture MSA\eurekaserver
      dockerfile: C:\Users\amino\OneDrive\Bureau\Architecture MSA\eurekaserver\dockerfile
    ports:
      - "8761:8761"
