FROM openjdk:8
COPY ./target/keycloak-springboot-microservice-0.0.1-SNAPSHOT.jar keycloak-springboot-microservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","keycloak-springboot-microservice-0.0.1-SNAPSHOT.jar"]